# Generated by Django 5.0.7 on 2024-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(max_length=60),
        ),
    ]
